/*
 * Modern UI.
 * Copyright (C) 2019-2023 BloCamLimb. All rights reserved.
 *
 * Modern UI is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * Modern UI is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with Modern UI. If not, see <https://www.gnu.org/licenses/>.
 */

package icyllis.arc3d.engine;

import javax.annotation.Nonnull;

/**
 * This class is used to generate a generic pipeline cache key. The Vulkan backend
 * derive backend-specific versions which add additional information.
 */
public final class PipelineDesc extends KeyBuilder {

    private int mShaderKeyLength;

    public PipelineDesc() {
    }

    /**
     * Returns the number of ints of the base key, without additional information.
     * The key in this range describes the shader module info. OpenGL has no additional
     * information, but Vulkan has.
     * <p>
     * Because Vulkan encapsulates some states into an immutable structure, we have to
     * collect additional information to form the cache key.
     */
    public int getShaderKeyLength() {
        return mShaderKeyLength;
    }

    /**
     * Builds a base pipeline descriptor, without additional information.
     *
     * @param desc the pipeline descriptor
     * @param info the pipeline information
     * @param caps the context capabilities
     */
    @Nonnull
    public static PipelineDesc build(PipelineDesc desc, PipelineInfo info, Caps caps) {
        desc.reset();
        genKey(desc, info, caps);
        desc.mShaderKeyLength = desc.length();
        return desc;
    }

    public static String describe(PipelineInfo info, Caps caps) {
        StringKeyBuilder b = new StringKeyBuilder();
        genKey(b, info, caps);
        return b.toString();
    }

    static void genKey(KeyBuilder b,
                       PipelineInfo info,
                       Caps caps) {
        genGPKey(info.geomProc(), b);

        //TODO more keys

        b.addBits(16, info.writeSwizzle(), "writeSwizzle");

        // Put a clean break between the "common" data written by this function, and any backend data
        // appended later. The initial key length will just be this portion (rounded to 4 bytes).
        b.flush();
    }

    /**
     * Functions which emit processor key info into the key builder.
     * For every effect, we include the effect's class ID (different for every GrProcessor subclass),
     * any information generated by the effect itself (addToKey), and some meta-information.
     * Shader code may be dependent on properties of the effect not placed in the key by the effect
     * (e.g. pixel format of textures used).
     */
    static void genGPKey(GeometryProcessor geomProc, KeyBuilder b) {
        b.appendComment(geomProc.name());
        // Currently we allow 8 bits for the class id
        b.addBits(8, geomProc.classID(), "gpClassID");

        geomProc.addToKey(b);
        geomProc.getAttributeKey(b);

        int numSamplers = geomProc.numTextureSamplers();
        b.addBits(4, numSamplers, "gpNumSamplers");
        for (int i = 0; i < numSamplers; i++) {
            b.addBits(16, geomProc.textureSamplerSwizzle(i), "swizzle");
        }
    }
}
